
const MONTHLY_CONTACTS_OBJ = null;
const MONTHLY_LEADS_OBJ = 200;
const MONTHLY_PROSPECTS_OBJ = 20;
const MONTHLY_ADVANCED_PROSPECTS_OBJ = 10;
const MONTHLY_CLIENTS_OBJ = 4;
const MONTHLY_EXPECTED_CA = 40000;
const MONTHLY_SIGNED_CA = 16000;

export {MONTHLY_CONTACTS_OBJ, MONTHLY_LEADS_OBJ, MONTHLY_PROSPECTS_OBJ, MONTHLY_ADVANCED_PROSPECTS_OBJ, MONTHLY_CLIENTS_OBJ, MONTHLY_EXPECTED_CA, MONTHLY_SIGNED_CA}